# Generated by Django 5.2.4 on 2025-07-08 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='komentar',
            name='user',
        ),
        migrations.AddField(
            model_name='kegiatan',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='komentar',
            name='nama',
            field=models.CharField(default='Anonim', max_length=100),
        ),
        migrations.AlterField(
            model_name='kegiatan',
            name='tanggal',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='komentar',
            name='kegiatan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kegiatan.kegiatan'),
        ),
    ]
