# Generated by Django 5.2.4 on 2025-07-08 14:18

import django.db.models.deletion
import django.utils.timezone
import kegiatan.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0002_remove_komentar_user_kegiatan_slug_komentar_nama_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kegiatan',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to=kegiatan.models.kegiatan_upload_path),
        ),
        migrations.AlterField(
            model_name='komentar',
            name='kegiatan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komentar', to='kegiatan.kegiatan'),
        ),
        migrations.AlterField(
            model_name='komentar',
            name='nama',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='komentar',
            name='tanggal',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
