# Generated by Django 5.2.4 on 2025-07-07 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=100)),
                ('tanggal_lahir', models.DateField()),
                ('angkatan', models.PositiveIntegerField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('no_telepon', models.CharField(blank=True, max_length=20, null=True)),
                ('status_saat_ini', models.CharField(choices=[('kerja', 'Bekerja'), ('kuliah', 'Kuliah'), ('menikah', 'Menikah'), ('lainnya', 'Lainnya')], max_length=20)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='foto_alumni/')),
            ],
        ),
        migrations.CreateModel(
            name='RiwayatPendidikan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenjang', models.CharField(max_length=50)),
                ('nama_institusi', models.CharField(max_length=100)),
                ('tahun_masuk', models.PositiveIntegerField()),
                ('tahun_lulus', models.PositiveIntegerField(blank=True, null=True)),
                ('alumni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_pendidikan', to='sistem_alumni.alumni')),
            ],
        ),
    ]
