# Generated by Django 5.2.4 on 2025-07-08 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistem_alumni', '0002_rename_alamat_alumni_deskripsi_singkat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='alamat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='no_hp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
