# Generated by Django 5.2.4 on 2025-07-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistem_alumni', '0003_alumni_alamat_alumni_no_hp'),
    ]

    operations = [
        migrations.CreateModel(
            name='KonfigurasiSitus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_tambah_alumni_aktif', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Konfigurasi Situs',
                'verbose_name_plural': 'Konfigurasi Situs',
            },
        ),
    ]
